// 编辑区样式分离，使用类名和必要的动态样式对象
export default {
  // 背景音乐上传面板样式
  uploadCard: {
    width: '100%',
    maxWidth: '400px',
    minHeight: '120px',
    background: 'rgba(255,255,255,0.95)',
    borderRadius: '15px',
    boxShadow: '0 2px 16px #0002',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: '18px 18px 18px 18px',
    margin: '18px auto 0 auto',
    position: 'static',
    zIndex: 20,
    gap: '18px'
  },
  uploadTitle: {
    color: '#ff9800',
    fontWeight: 'bold',
    fontSize: '1.08rem',
    marginBottom: '10px',
    textAlign: 'center',
    letterSpacing: '1px'
  },
  uploadForm: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    marginBottom: '8px'
  },
  uploadInput: {
    padding: '7px 12px',
    borderRadius: '7px',
    border: '1px solid #ff980055',
    background: '#fff',
    color: '#333',
    fontSize: '1rem',
    outline: 'none',
    width: '80%',
    marginBottom: '4px',
    boxSizing: 'border-box',
    transition: 'border 0.2s, background 0.2s'
  },
  uploadFileInput: {
    color: '#333',
    background: '#fff',
    borderRadius: '7px',
    border: '1px solid #ff980055',
    fontSize: '1rem',
    padding: '6px 8px',
    cursor: 'pointer',
    width: '80%',
    marginBottom: '4px',
    boxSizing: 'border-box'
  },
  uploadBtn: {
    padding: '8px 22px',
    borderRadius: '9px',
    background: 'linear-gradient(90deg,#ff9800 60%,#ffc107 100%)',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: '1.08rem',
    border: 'none',
    boxShadow: '0 2px 8px #ff980033',
    cursor: 'pointer',
    marginTop: '6px',
    transition: 'background 0.2s, box-shadow 0.2s'
  },
  uploadBtnDisabled: {
    background: '#bbb',
    color: '#eee',
    cursor: 'not-allowed',
    boxShadow: 'none'
  },
  uploadTip: {
    color: '#ff9800',
    fontSize: '0.98rem',
    marginTop: '4px',
    textAlign: 'center',
    fontWeight: 'bold'
  },
  editPanel: {
    width: '100%',
    minHeight: '320px',
    background: 'rgba(255,255,255,0.10)',
    borderRadius: '16px',
    boxShadow: '0 2px 16px #0834ff22',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 18px',
    position: 'relative',
    overflow: 'hidden',
  },
  editForm: {
    width: '100%',
    maxWidth: '420px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
  },
  editInput: {
    padding: '6px 10px',
    borderRadius: '6px',
    border: '1px solid #eaeaea',
    background: 'rgba(255,255,255,0.12)',
    color: '#333',
    fontSize: '0.98rem',
    outline: 'none',
    transition: 'border 0.2s, background 0.2s',
  },
  editBtn: {
    padding: '7px 18px',
    borderRadius: '8px',
    background: 'linear-gradient(90deg,#0834ff 60%,#4f8cff 100%)',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: '1rem',
    border: 'none',
    boxShadow: '0 2px 8px #0834ff33',
    cursor: 'pointer',
    transition: 'background 0.2s, box-shadow 0.2s',
  },
  editBtnDisabled: {
    background: '#bbb',
    color: '#eee',
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  editTip: {
    color: '#0834ff',
    fontSize: '0.92rem',
    marginTop: '2px',
    textAlign: 'center',
  },
  tagInput: {
    padding: '4px 8px',
    borderRadius: '8px',
    border: '1px solid #eaeaea',
    background: '#f5f7fa',
    color: '#0834ff',
    fontSize: '0.95rem',
    marginRight: '6px',
    outline: 'none',
  },
  tagBtn: {
    padding: '3px 10px',
    borderRadius: '8px',
    background: 'linear-gradient(90deg,#e6f0ff 0%,#f0f4ff 100%)',
    color: '#0834ff',
    fontWeight: 'bold',
    fontSize: '0.95rem',
    border: 'none',
    boxShadow: '0 1px 4px #eee',
    cursor: 'pointer',
    marginLeft: '4px',
  },
};